"""six

Revision ID: 0df43b341620
Revises: bb43bb63f946
Create Date: 2026-08-03 17:45:21.954292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df43b341620'
down_revision: Union[str, Sequence[str], None] = 'bb43bb63f946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_collections', sa.Column('slug_tag', sa.String(length=200), nullable=True))
    op.add_column('sub_collections', sa.Column('title_tag', sa.String(length=200), nullable=True))
    op.add_column('sub_collections', sa.Column('description_tag', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'sub_collections', ['slug_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_collections', type_='unique')
    op.drop_column('sub_collections', 'description_tag')
    op.drop_column('sub_collections', 'title_tag')
    op.drop_column('sub_collections', 'slug_tag')
    # ### end Alembic commands ###
