"""seven

Revision ID: 28470cf84a86
Revises: 0df43b341620
Create Date: 2026-08-09 13:54:45.796276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28470cf84a86'
down_revision: Union[str, Sequence[str], None] = '0df43b341620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug_tag', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('title_tag', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('description_tag', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'products', ['slug_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'description_tag')
    op.drop_column('products', 'title_tag')
    op.drop_column('products', 'slug_tag')
    # ### end Alembic commands ###
