"""five

Revision ID: bb43bb63f946
Revises: 3221ab23870f
Create Date: 2026-08-03 16:02:22.247771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb43bb63f946'
down_revision: Union[str, Sequence[str], None] = '3221ab23870f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('slug_tag', sa.String(length=200), nullable=True))
    op.add_column('collections', sa.Column('title_tag', sa.String(length=200), nullable=True))
    op.add_column('collections', sa.Column('description_tag', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'description_tag')
    op.drop_column('collections', 'title_tag')
    op.drop_column('collections', 'slug_tag')
    # ### end Alembic commands ###
