"""Initial migration 3

Revision ID: bd8ffdfdf9f6
Revises: a228e81023ea
Create Date: 2025-07-17 12:20:44.385737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd8ffdfdf9f6"
down_revision: Union[str, Sequence[str], None] = "a228e81023ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=35), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=10, scale=0), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_path", sa.String(length=250), nullable=False),
        sa.Column(
            "menu",
            sa.Enum("CASUAL", "SPECIAL", name="productionmenuenums"),
            nullable=False,
        ),
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_unique_constraint(None, "collections", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "collections", type_="unique")
    op.drop_table("products")
    # ### end Alembic commands ###
