"""one

Revision ID: de2d81967031
Revises:
Create Date: 2026-08-17 15:49:10.609451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "de2d81967031"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("image", sa.String(length=200), nullable=False),
        sa.Column("slug_tag", sa.String(length=200), nullable=True),
        sa.Column("title_tag", sa.String(length=200), nullable=True),
        sa.Column("description_tag", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "desktop_banners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("image", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "phone_banners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("image", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "scrolls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("scroll", sa.String(length=200), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=False),
        sa.Column("query", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scroll"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "social_apps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("link", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "sub_collections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("image", sa.String(length=200), nullable=False),
        sa.Column("slug_tag", sa.String(length=200), nullable=True),
        sa.Column("title_tag", sa.String(length=200), nullable=True),
        sa.Column("description_tag", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
        sa.UniqueConstraint("slug_tag"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=60), nullable=False),
        sa.Column("phone_number", sa.String(length=11), nullable=False),
        sa.Column("password", sa.String(length=250), nullable=False),
        sa.Column(
            "user_type", sa.Enum("admin", "customer", name="usertype"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("discounted_price", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "not_available", name="statustype"),
            nullable=False,
        ),
        sa.Column(
            "menu", sa.Enum("casual", "special", name="menutype"), nullable=False
        ),
        sa.Column(
            "scroll",
            sa.Enum(
                "none",
                "scroll_1",
                "scroll_2",
                "scroll_3",
                "scroll_4",
                name="scrolltype",
            ),
            nullable=False,
        ),
        sa.Column("slug_tag", sa.String(length=200), nullable=True),
        sa.Column("title_tag", sa.String(length=200), nullable=True),
        sa.Column("description_tag", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("sub_collection_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"], ["collections.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sub_collection_id"], ["sub_collections.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug_tag"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("image", sa.String(length=300), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("image"),
    )
    op.create_table(
        "product_information",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=150), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "key", "product_id", name="uq_product_information_key_product_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_information")
    op.drop_table("product_images")
    op.drop_table("products")
    op.drop_table("users")
    op.drop_table("sub_collections")
    op.drop_table("social_apps")
    op.drop_table("scrolls")
    op.drop_table("phone_banners")
    op.drop_table("desktop_banners")
    op.drop_table("collections")
    op.execute("DROP TYPE statustype")
    op.execute("DROP TYPE menutype")
    op.execute("DROP TYPE scrolltype")
    op.execute("DROP TYPE usertype")
    # ### end Alembic commands ###
